version: '3.4'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8800:8800
    networks:
      - app-network

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - app-network

  socket:
    image: socket
    build:
      context: ./socket
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8900:8900
    networks:
      - app-network

networks:
  app-network:
    driver: bridge