version: '3.4'

services:
  socket:
    image: socket
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8900:8900
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
